spring.application.name=HomeCart

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.datasource.hikari.data-source-properties.trustCertificateKeyStoreUrl=${SSL_TRUSTSTORE}
spring.datasource.hikari.data-source-properties.trustCertificateKeyStorePassword=${SSL_TRUSTSTORE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration